version: '3'
services:
  postgres:
    container_name: rosatom_postgres
    image: postgres:13
    restart: always
    volumes:
      - psql_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

volumes:
  psql_data:


