# Generated by Django 3.1 on 2021-12-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oilspillregion',
            options={'verbose_name': 'Oil spill Region relation', 'verbose_name_plural': 'Oil spill Region relations'},
        ),
    ]
